// import React from "react";
// import "../../index.css";
// import "./Course.css";
// import { courseData } from "../../data";
// import { useParams } from "react-router-dom";
// import MyNavbar from "../../components/navbar/Navbar";
// import { Container, Row, Col } from "react-bootstrap";

// function Course() {
//   // Get the courseId from the URL params
//   const courseId = useParams().courseId;

//   // Find the course by its ID (ensure both are of the same type)
//   const courseInfo = courseData.find(
//     (course) => course.id === Number(courseId)
//   );

//   // If no course is found, you can show an error or fallback content
//   if (!courseInfo) {
//     return <div>Course not found</div>;
//   }

//   return (
//     <div>
//       <MyNavbar />
//       <Container>
//         <Row className="align-items-center">
//           <Col md={5}>
//             <img
//               className="img-fluid"
//               src={courseInfo.img}
//               alt={courseInfo.title}
//               style={{ maxWidth: "100%", height: "auto" }}
//             />
//           </Col>
//           <Col md={7} className="my-3">
//             <h2 style={{ fontFamily: "lalezar" }}>{courseInfo.title}</h2>
//             <p className="lalezar">Teacher: {courseInfo.teacher}</p>
//             <p>
//               <b>{courseInfo.text}</b>
//             </p>
//             <p style={{ textAlign: "justify" }}>
//               Lorem Ipsum is a placeholder text generated by the printing
//               industry to create an unreadable, simplistic output. Lorem Ipsum
//               is a placeholder text generated by the printing industry to create
//               an unreadable, simplistic output. Lorem Ipsum is a placeholder
//               text generated by the printing industry to create an unreadable,
//               simplistic output. Lorem Ipsum is a placeholder text generated by
//               the printing industry to create an unreadable, simplistic output.
//               Lorem Ipsum is a placeholder text generated by the printing
//               industry to create an unreadable, simplistic output. Lorem Ipsum
//               is a placeholder text generated by the printing industry to create
//               an unreadable, simplistic output.Lorem Ipsum is a placeholder text
//               generated by the printing industry to create an unreadable,
//               simplistic output
//             </p>
//           </Col>
//         </Row>
//       </Container>
//     </div>
//   );
// }

// export default Course;

// import React from "react";
// import "../../index.css";
// import "./Course.css";
// import { courseData } from "../../data";
// import { useParams } from "react-router-dom";
// import MyNavbar from "../../components/navbar/Navbar";
// import { Container, Row, Col, Button } from "react-bootstrap"; // Importing Button component

// function Course() {
//   // Get the courseId from the URL params
//   const courseId = useParams().courseId;

//   // Find the course by its ID (ensure both are of the same type)
//   const courseInfo = courseData.find(
//     (course) => course.id === Number(courseId)
//   );

//   // If no course is found, you can show an error or fallback content
//   if (!courseInfo) {
//     return (
//       <div className="text-center mt-5">
//         <h3>Course Not Found</h3>
//         <p>Sorry, we couldn't find the course you're looking for.</p>
//         <Button variant="primary" href="/courses">
//           Go Back to Courses
//         </Button>
//       </div>
//     );
//   }

//   return (
//     <div>
//       <MyNavbar />
//       <Container className="my-5">
//         <Row className="align-items-center">
//           <Col md={5} className="mb-4 mb-md-0">
//             <img
//               className="img-fluid rounded"
//               src={courseInfo.img}
//               alt={courseInfo.title}
//             />
//           </Col>
//           <Col md={7}>
//             <h2 className="display-4 text-primary">{courseInfo.title}</h2>
//             <p className="h5 text-muted lalezar">
//               Teacher: {courseInfo.teacher}
//             </p>
//             <p className="lead">{courseInfo.text}</p>
//             <p className="text-justify">
//               Lorem Ipsum is a placeholder text generated by the printing
//               industry to create an unreadable, simplistic output. Lorem Ipsum
//               is a placeholder text generated by the printing industry to create
//               an unreadable, simplistic output. Lorem Ipsum is a placeholder
//               text generated by the printing industry to create an unreadable,
//               simplistic output. Lorem Ipsum is a placeholder text generated by
//               the printing industry to create an unreadable, simplistic output.
//               Lorem Ipsum is a placeholder text generated by the printing
//               industry to create an unreadable, simplistic output. Lorem Ipsum
//               is a placeholder text generated by the printing industry to create
//               an unreadable, simplistic output. Lorem Ipsum is a placeholder
//               text generated by the printing industry to create an unreadable,
//               simplistic output.
//             </p>
//             <Button variant="success" size="lg" href="#enroll">
//               Enroll Now
//             </Button>
//           </Col>
//         </Row>
//       </Container>
//     </div>
//   );
// }

// export default Course;

import React from "react";
import "../../index.css";
import "./Course.css";
import { courseData } from "../../data";
import { useParams, useNavigate } from "react-router-dom"; // Importing useNavigate
import MyNavbar from "../../components/navbar/Navbar";
import { Container, Row, Col, Button } from "react-bootstrap"; // Importing Button component

function Course() {
  // Get the courseId from the URL params
  const courseId = useParams().courseId;

  // Find the course by its ID (ensure both are of the same type)
  const courseInfo = courseData.find(
    (course) => course.id === Number(courseId)
  );

  // If no course is found, you can show an error or fallback content
  if (!courseInfo) {
    return (
      <div className="text-center mt-5">
        <h3>Course Not Found</h3>
        <p>Sorry, we couldn't find the course you're looking for.</p>
        <Button variant="primary" href="/courses">
          Go Back to Courses
        </Button>
      </div>
    );
  }

  // Using useNavigate to handle navigation programmatically
  const navigate = useNavigate();

  // Function to handle enroll button click
  const handleEnrollClick = () => {
    navigate("/notFound"); // Redirect to the "/notFound" page
  };

  return (
    <div>
      <MyNavbar />
      <Container className="my-5">
        <Row className="align-items-center">
          <Col md={5} className="mb-4 mb-md-0">
            <img
              className="img-fluid rounded"
              src={courseInfo.img}
              alt={courseInfo.title}
            />
          </Col>
          <Col md={7}>
            <h2 className="display-4 text-primary">{courseInfo.title}</h2>
            <p className="h5 text-muted lalezar">
              Teacher: {courseInfo.teacher}
            </p>
            <p className="lead">{courseInfo.text}</p>
            <p className="text-justify">
              Lorem Ipsum is a placeholder text generated by the printing
              industry to create an unreadable, simplistic output. Lorem Ipsum
              is a placeholder text generated by the printing industry to create
              an unreadable, simplistic output.
            </p>
            <Button
              variant="success"
              size="lg"
              onClick={handleEnrollClick} // Using onClick to handle the navigation
            >
              Enroll Now
            </Button>
          </Col>
        </Row>
      </Container>
    </div>
  );
}

export default Course;
