import React from "react";
import "./Course.css";
import { courseData } from "../../data";
import { useParams } from "react-router-dom";
import MyNavbar from "../../components/navbar/Navbar";
import { Container, Row, Col } from "react-bootstrap";
function Course() {
  const courseId = useParams().courseId;
  const courseInfo = courseData.find((course) => (course.id = courseId));
  return (
    <div>
      <MyNavbar />
      <Container>
        <Row className="align-items-center">
          <Col md={5}>
            <img src={courseInfo.img} />
          </Col>
          <Col md={7} className="my-3">
            <h2 style={{ fontFamily: "lalezar" }}>{courseInfo.title}</h2>
            <p>Teacher : {courseInfo.teacher} </p>
            <p>
              <b>{courseInfo.text}</b>
            </p>
            <p style={{ textAlign: "justify" }}>
              Lorem Ipsum is a placeholder text generated by the printing
              industry to create an unreadable, simplistic output. It is used by
              graphic designers, printers, and text creators, as well as
              newspapers and magazines, in columns and rows as needed. It serves
              current technological needs and has various applications aimed at
              improving practical tools. Many books, covering sixty-three
              percent of the past, present, and future, require a deep
              understanding of society and experts. This understanding will help
              designers, especially creative ones, use software to expand their
              knowledge, promoting a progressive culture in the Persian
              language. In this way, it is hoped that all difficulties in
              providing solutions and the challenges of typography will be
              overcome, and the necessary time, including typesetting, will
              focus on the main achievements, addressing ongoing questions from
              the world of design, which will essentially be used.
            </p>
          </Col>
        </Row>
      </Container>
    </div>
  );
}

export default Course;
